### ISSUE TITLE
[BUG] Ammo dupe

### ISSUE THREAD

**Issue by luucayy** [WeaponMechanics/MechanicsMain#444]
### Current/Expected Behavior

Bullets from any weapon can be duped using the secondary/off hand.

The bullets that are duped are those that are in the weapon's chamber, for example AUG has 20 bullets in the chamber (not 30 which is the maximum) and by performing the bug process you will be duped 20+20+20+20 by spamming

### Steps To Reproduce

1. Have a weapon in hand
2. Use the hotkey to change the hand item (Default: F)
3. Do this process by spamming the F hotkey

### Log File

The log file is not needed, it is a bug that I found in all versions

**Comment by luucayy** [comment]
Added:

- I tested the error in different versions of Spigot and Paper, in all of them it works (I did not check in Purpur but it would be logical that it happens the same)
- I tested from version 3.2.7 to the current 3.4.9 and it works in all versions in between

I am also using Paperspigot 1.19.4 (Build #550, latest)

**Comment by CJCrafter** [comment]
Fixed in #458

**Comment by xtb7** [comment]
As of release v3.5.1, this bug is still active.

To fix this issue, I had to change all of my .yml files defining my weapons. Here's the Reload section of my AK_47.yml before and after:

Before:
`Reload:
    Ammo:
      Out_Of_Ammo_Mechanics:
        - "Message{message=You need more ammo to reload this gun!}"
      Ammo_Switch_Trigger: 
        Main_Hand: SWAP_HANDS
        Off_Hand: SWAP_HANDS
      Ammo_Switch_Mechanics: 
      Ammos:
        - MediumAmmo
    Trigger:
      Main_Hand: "DROP_ITEM"
      Off_Hand: "DROP_ITEM"
    Magazine_Size: 30
    Reload_Duration: 57
    Start_Mechanics:
      - "CustomSound{sound=reload.start.normal, volume=0.5, noise=0.1}"
    Finish_Mechanics:
      - "CustomSound{sound=reload.end.normal, volume=0.5, noise=0.1}"`  

After:
`Reload:
    Ammo:
      Out_Of_Ammo_Mechanics:
        - "Message{message=You need more ammo to reload this gun!}"
      Ammos:
        - MediumAmmo
    Trigger:
      Main_Hand: "DROP_ITEM"
      Off_Hand: "DROP_ITEM"
    Magazine_Size: 30
    Reload_Duration: 57
    Start_Mechanics:
      - "CustomSound{sound=reload.start.normal, volume=0.5, noise=0.1}"
    Finish_Mechanics:
      - "CustomSound{sound=reload.end.normal, volume=0.5, noise=0.1}"`

I don't know if this bug is still active in the build that is supposed to fix it, or if that fix just wasn't included in this latest release.
